version: '3'
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: oportuniza-plataforma
    restart: always
    ports:
      - '8080:8080'
    env_file: .env
